### ISSUE TITLE
 Cannot connect to host

### ISSUE THREAD

**Issue by mrflyman** [thehamkercat/LunaChatBot#13]
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host thearq.tech:443 ssl:default [Connect call failed ('', 443)]

I'm getting an error like this on heroku

**Comment by TheHamkerCat** [comment]
Change ARQ_API_URL in config.py to `https://grambuilders.tech`

**Comment by mrflyman** [comment]
I've already changed the URL. I'm getting this error, I use Heroku

**Comment by TheHamkerCat** [comment]
You aren't

**Comment by mrflyman** [comment]
I solved the problem thank you

**Comment by itzzzyashu** [comment]
> https://grambuilders.tech



> I solved the problem thank you

How did you solved this error?
