### ISSUE TITLE
Nokogiri error 

### ISSUE THREAD

**Issue by the-arxyn** [thehamkercat/LunaChatBot#22]
Hello bro while deploying my fork of your Luna telegram bot repo there was an error of nokogiri version and libxslt and libxml please tell me how to fix it i have tried on heroheroku ,clever cloud and render all showed same error 
![Screenshot_20230314_190918](https://user-images.githubusercontent.com/89521876/225019661-8e41405e-7895-4b66-b752-95090a9ee776.jpg)

**Comment by TheHamkerCat** [comment]
nokogiri?

**Comment by the-arxyn** [comment]
> nokogiri?
Yes bro see the screenshots (logs)😊

**Comment by the-arxyn** [comment]
wtf y u closed the issue without solving
